### ISSUE TITLE
Event from command line

### ISSUE THREAD

**Issue by pmosconi** [Max-Kolodezniy/aws-lambda-local#10]
Hi,
I have a use case where the event should be passed directly from command line instead of read from file.
I made a very simple change to the code and I'd be happy to provide a pull request for it  if you are interested.

**Comment by Max-Kolodezniy** [comment]
Go ahead and submit your request. Thank you!

чт, 13 вер. 2018, 12:50 користувач pmosconi <notifications@github.com> пише:

**Comment by Max-Kolodezniy** [comment]
Thank you for submitting the request.

I have actually changed the logic for avoid any unnecessary parameters or parameters that may be omitted.
So, I have expanded the -e parameter value, now it can be either filename or JSON string.

In addition, I have added the ability to pass input thru STDIN. Please, refer to the latest doc
