### ISSUE TITLE
Any plans to convert to TypeScript ?

### ISSUE THREAD

**Issue by StefH** [Max-Kolodezniy/aws-lambda-local#2]
I was thinking to create a PR to convert this project to TypeScript, is that a good idea ?

**Comment by Max-Kolodezniy** [comment]
What is the purpose of TypeScripting? This module was designed as native node.js module that just works. What improvement will be done on these 160 lines of code with TypeScript?

**Comment by StefH** [comment]
Typescript provides some more structure and error checking while typing the code.

I am used to c# and typescript just makes javascript less magic...

But indeed, maybe for this project it's not really needed...  I will take a quick look...
