### ISSUE TITLE
How to call if the name from the function is not "handler" ?

### ISSUE THREAD

**Issue by StefH** [Max-Kolodezniy/aws-lambda-local#3]
Currently my file **handler.js**, has this code

``` js
exports.handleIt = function (event, context, callback) {
    callback(null, { message: 'hello' });
};
```

`lambda-local --function handler.js` shows error like:

> node_modules\aws-lambda-local\lambda-local.js:138
>     require(name).handler(event, context, function(error, output) {
>                   ^
> 
> TypeError: require(...).handler is not a function

Shouldn't there be an additional parameter like **handler**?

Suggedted command should be like `lambda-local --handler handler.js --function handleIt` where the function will fallback to the value "handler" ?

**Comment by Max-Kolodezniy** [comment]
Just name it exports.handler
That will work in both local and AWS environments.

**Comment by Max-Kolodezniy** [comment]
I'll try to think about it. Maybe analyze the exports and call the first property

**Comment by StefH** [comment]
Note that AWS doe snot enforce the name, so I can choose whatever name I want.

Indeed, calling the first function is also an option. Please keep me updated...

For details, you can also checkout other project https://github.com/sbarski/run-local-lambda

**Comment by Max-Kolodezniy** [comment]
Please, reinstall package with **npm install -g aws-lambda-local**
Now first function from exports will be used as handler.
