### ISSUE TITLE
node_modules/.bin/ install

### ISSUE THREAD

**Issue by jghaines** [Max-Kolodezniy/aws-lambda-local#5]
I'm using lambda-local in my devDependencies of my system and my npm test function calls it by running ./node_modules/.bin/lambda-local

I'd like to replace lambda-local with aws-lambda-local without having to force users of my package to do a global install.

**Comment by Max-Kolodezniy** [comment]
Not sure I completely understand what you mean.
In both unix and windows systems you can invoke lambda-local with node lambda-local.js ...
Unix-only way exists too - shebang: chmod +x lambda-local.js and just run it

And "bin" section from package.json does the same
`"lambda-local"  : "./lambda-local.js"` just places symlink

```
➜ ll /usr/local/bin/lambda-local
lrwxr-xr-x  1 max  admin    52B 17 nov  2015 /usr/local/bin/lambda-local -> ../lib/node_modules/aws-lambda-local/lambda-local.js
```

to the npm package file and makes it executable

**Comment by jghaines** [comment]
Sorry, you are absolutely right - a devDependencies install will result in a useable ./node_modules/.bin/lambda-local

I think my prior lambda-local lib install caused the confusion.

I guess it would be nice to document the non-global/devDependencies install variant.
