### ISSUE TITLE
Debug support

### ISSUE THREAD

**Issue by sigrist** [Max-Kolodezniy/aws-lambda-local#6]
How about add a debug support?

**Comment by Max-Kolodezniy** [comment]
What kind of debug information you're expecting to have? Memory
consumption, execution time? Just give me an idea.

8 бер. 2017 р. 05:29 "Paulo Sigrist" <notifications@github.com> пише:

**Comment by Max-Kolodezniy** [comment]
I'm closing this issue since there was no answers from topic starter
