### ISSUE TITLE
Non-zero exit code

### ISSUE THREAD

**Issue by mgoodings** [Max-Kolodezniy/aws-lambda-local#9]
Can you please add a non-zero exit code for any failures

**Comment by Max-Kolodezniy** [comment]
Hello!

Thank you for your comment, I really appreciate it.
You are right, ability to have code > 0 is useful enough for include it to the distribution.

See code here: https://github.com/Max-Kolodezniy/aws-lambda-local/commit/888ff5d46646d7858c23077b8f28a290cfef8695

**Comment by Max-Kolodezniy** [comment]
```
'use strict';

exports.handler = (event, context, callback) =>
{
    callback('error');
}

➜ lambda-local -f index.js -t 10
ERROR
--------------------------------
{
    "errorMessage": "error"
}
➜  echo $?                                                                                               
1
```
